version: "3.8"

services:

  web:
    build: .
    command: sh ./docker-entrypoint.sh
    volumes:
      - data:/app/data/
    ports:
      - "8001:8000"
    env_file:
      - ./.env
    depends_on:
      - db

  fetch:
    build: .
    command: sh ./docker-entrypoint-fetch.sh
    env_file:
      - ./.env
    depends_on:
      - db
    volumes:
      - ./:/app/

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  influx:
    image: influxdb:2.5.1
    ports:
      - "8087:8086"
    volumes:
      - influxdb:/var/lib/influxdb
      - influxdb2:/var/lib/influxdb2
    env_file:
      - ./.env
volumes:
  data:
  postgres_data:
  influxdb:
  influxdb2: